predicates:
  - name: 'birthPlace'
    uri: 'http://dbpedia.org/ontology/birthPlace'
    samples_download: false
    words:
      - 'born'
    not_words:
      - 'play'
      - 'played'
      - 'match'
      - 'win'
      - 'won'
      - 'died'
      - 'death'
    dev_pages:
    test_pages:
      - 'Thomas Jefferson'
      - 'Rita Levi-Montalcini'
      - 'Anthony Kiedis'
      - 'Zinedine Zidane'
      - 'Elon Musk'
      - 'Linus Torvalds'
      - 'Kevin Campbell'
      - 'Andrew Jackson'
      - 'Francesco Totti'
      - 'George Washington'
      - 'Grover Cleveland'
      - 'John Quincy Adams'
      - 'Roger Waters'
      - 'Alessandro Del Piero'
      - 'Archie Roe'
      - 'Dave Halliday'
      - 'Mark Flatts'
  - name: 'spouse'
    samples_download: true
    uri: 'http://dbpedia.org/ontology/spouse'
    words:
      - 'spouse'
      - 'wife'
      - 'husband'
      - 'ex-wife'
      - 'ex-husband'
      - 'married'
    not_words:
      - 'father'
      - 'mother'
      - 'sister'
      - 'brother'
      - 'son'
      - 'daughter'
      - 'grandfather'
      - 'grandmother'
      - 'uncle'
      - 'aunt'
      - 'cousin'
      - 'boyfriend'
      - 'girlfriend'
      - 'boss'
      - 'employee'
      - 'secretary'
      - 'co-worker'
    dev_pages:
    test_pages:
      - 'Thomas Jefferson'
      - 'Rita Levi-Montalcini'
      - 'Anthony Kiedis'
      - 'Zinedine Zidane'
      - 'Elon Musk'
      - 'Linus Torvalds'
      - 'Kevin Campbell'
      - 'Andrew Jackson'
      - 'Francesco Totti'
      - 'George Washington'
      - 'Grover Cleveland'
      - 'John Quincy Adams'
      - 'Roger Waters'
      - 'Alessandro Del Piero'
      - 'Archie Roe'
      - 'Dave Halliday'
      - 'Mark Flatts'
#  - name: 'team'
#    samples_download: true
#    uri: 'http://dbpedia.org/ontology/team'
#    words:
#      - 'played'
#      - 'signed'
#      - 'sign'
#      - 'transfer'
#      - 'transferred'
#    not_words:
#      - 'live'
#      - 'against'
#    dev_pages:
#    test_pages:
#      - 'Thomas Jefferson'
#      - 'Rita Levi-Montalcini'
#      - 'Anthony Kiedis'
#      - 'Zinedine Zidane'
#      - 'Elon Musk'
#      - 'Linus Torvalds'
#      - 'Kevin Campbell'
#      - 'Andrew Jackson'
#      - 'Francesco Totti'
#      - 'George Washington'
#      - 'Grover Cleveland'
#      - 'John Quincy Adams'
#      - 'Roger Waters'
#      - 'Alessandro Del Piero'
#      - 'Archie Roe'
#      - 'Dave Halliday'
#      - 'Mark Flatts'





